<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MapCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('map_countries')->delete();

        $countries = array(
            array('name' => 'Afghanistan', 'abbr' => 'AFG'),
            array('name' => 'Angola', 'abbr' => 'AGO'),
            array('name' => 'Albania', 'abbr' => 'ALB'),
            array('name' => 'United Arab Emirates', 'abbr' => 'ARE'),
            array('name' => 'Argentina', 'abbr' => 'ARG'),
            array('name' => 'Armenia', 'abbr' => 'ARM'),
            array('name' => 'Antarctica', 'abbr' => 'ATA'),
            array('name' => 'French Southern and Antarctic Lands', 'abbr' => 'ATF'),
            array('name' => 'Australia', 'abbr' => 'AUS'),
            array('name' => 'Austria', 'abbr' => 'AUT'),
            array('name' => 'Azerbaijan', 'abbr' => 'AZE'),
            array('name' => 'Burundi', 'abbr' => 'BDI'),
            array('name' => 'Belgium', 'abbr' => 'BEL'),
            array('name' => 'Benin', 'abbr' => 'BEN'),
            array('name' => 'Burkina Faso', 'abbr' => 'BFA'),
            array('name' => 'Bangladesh', 'abbr' => 'BGD'),
            array('name' => 'Bulgaria', 'abbr' => 'BGR'),
            array('name' => 'Bosnia and Herzegovina', 'abbr' => 'BIH'),
            array('name' => 'The Bahamas', 'abbr' => 'BHS'),
            array('name' => 'Belarus', 'abbr' => 'BLR'),
            array('name' => 'Belize', 'abbr' => 'BLZ'),
            array('name' => 'Bolivia', 'abbr' => 'BOL'),
            array('name' => 'Brazil', 'abbr' => 'BRA'),
            array('name' => 'Brunei', 'abbr' => 'BRN'),
            array('name' => 'Bhutan', 'abbr' => 'BTN'),
            array('name' => 'Botswana', 'abbr' => 'BWA'),
            array('name' => 'Central African Republic', 'abbr' => 'CAF'),
            array('name' => 'Canada', 'abbr' => 'CAN'),
            array('name' => 'Switzerland', 'abbr' => 'CHE'),
            array('name' => 'Chile', 'abbr' => 'CHL'),
            array('name' => 'China', 'abbr' => 'CHN'),
            array('name' => 'Ivory Coast', 'abbr' => 'CIV'),
            array('name' => 'Cameroon', 'abbr' => 'CMR'),
            array('name' => 'Democratic Republic of the Congo', 'abbr' => 'COD'),
            array('name' => 'Republic of the Congo', 'abbr' => 'COG'),
            array('name' => 'Colombia', 'abbr' => 'COL'),
            array('name' => 'Costa Rica', 'abbr' => 'CRI'),
            array('name' => 'Cuba', 'abbr' => 'CUB'),
            array('name' => 'Northern Cyprus', 'abbr' => 'NCYP'),
            array('name' => 'Cyprus', 'abbr' => 'CYP'),
            array('name' => 'Czech Republic', 'abbr' => 'CZE'),
            array('name' => 'Germany', 'abbr' => 'DEU'),
            array('name' => 'Djibouti', 'abbr' => 'DJI'),
            array('name' => 'Denmark', 'abbr' => 'DNK'),
            array('name' => 'Dominican Republic', 'abbr' => 'DOM'),
            array('name' => 'Algeria', 'abbr' => 'DZA'),
            array('name' => 'Ecuador', 'abbr' => 'ECU'),
            array('name' => 'Egypt', 'abbr' => 'EGY'),
            array('name' => 'Eritrea', 'abbr' => 'ERI'),
            array('name' => 'Spain', 'abbr' => 'ESP'),
            array('name' => 'Estonia', 'abbr' => 'EST'),
            array('name' => 'Ethiopia', 'abbr' => 'ETH'),
            array('name' => 'Finland', 'abbr' => 'FIN'),
            array('name' => 'Falkland Islands', 'abbr' => 'FLK'),
            array('name' => 'Fiji', 'abbr' => 'FJI'),
            array('name' => 'France', 'abbr' => 'FRA'),
            array('name' => 'French Guiana', 'abbr' => 'GUF'),
            array('name' => 'Gabon', 'abbr' => 'GAB'),
            array('name' => 'United Kingdom', 'abbr' => 'GBR'),
            array('name' => 'Georgia', 'abbr' => 'GEO'),
            array('name' => 'Ghana', 'abbr' => 'GHA'),
            array('name' => 'Guinea', 'abbr' => 'GIN'),
            array('name' => 'Gambia', 'abbr' => 'GMB'),
            array('name' => 'Guinea Bissau', 'abbr' => 'GNB'),
            array('name' => 'Equatorial Guinea', 'abbr' => 'GNQ'),
            array('name' => 'Greece', 'abbr' => 'GRC'),
            array('name' => 'Greenland', 'abbr' => 'GRL'),
            array('name' => 'Guatemala', 'abbr' => 'GTM'),
            array('name' => 'Guyana', 'abbr' => 'GUY'),
            array('name' => 'Honduras', 'abbr' => 'HND'),
            array('name' => 'Croatia', 'abbr' => 'HRV'),
            array('name' => 'Haiti', 'abbr' => 'HTI'),
            array('name' => 'Hungary', 'abbr' => 'HUN'),
            array('name' => 'Indonesia', 'abbr' => 'IDN'),
            array('name' => 'India', 'abbr' => 'IND'),
            array('name' => 'Ireland', 'abbr' => 'IRL'),
            array('name' => 'Iran', 'abbr' => 'IRN'),
            array('name' => 'Iraq', 'abbr' => 'IRQ'),
            array('name' => 'Iceland', 'abbr' => 'ISL'),
            array('name' => 'Israel', 'abbr' => 'ISR'),
            array('name' => 'Italy', 'abbr' => 'ITA'),
            array('name' => 'Jamaica', 'abbr' => 'JAM'),
            array('name' => 'Jordan', 'abbr' => 'JOR'),
            array('name' => 'Japan', 'abbr' => 'JPN'),
            array('name' => 'Kazakhstan', 'abbr' => 'KAZ'),
            array('name' => 'Kenya', 'abbr' => 'KEN'),
            array('name' => 'Kyrgyzstan', 'abbr' => 'KGZ'),
            array('name' => 'Cambodia', 'abbr' => 'KHM'),
            array('name' => 'South Korea', 'abbr' => 'KOR'),
            array('name' => 'Kosovo', 'abbr' => 'KSV'),
            array('name' => 'Kuwait', 'abbr' => 'KWT'),
            array('name' => 'Laos', 'abbr' => 'LAO'),
            array('name' => 'Lebanon', 'abbr' => 'LBN'),
            array('name' => 'Liberia', 'abbr' => 'LBR'),
            array('name' => 'Libya', 'abbr' => 'LBY'),
            array('name' => 'Sri Lanka', 'abbr' => 'LKA'),
            array('name' => 'Lesotho', 'abbr' => 'LSO'),
            array('name' => 'Lithuania', 'abbr' => 'LTU'),
            array('name' => 'Luxembourg', 'abbr' => 'LUX'),
            array('name' => 'Latvia', 'abbr' => 'LVA'),
            array('name' => 'Morocco', 'abbr' => 'MAR'),
            array('name' => 'Moldova', 'abbr' => 'MDA'),
            array('name' => 'Madagascar', 'abbr' => 'MDG'),
            array('name' => 'Mexico', 'abbr' => 'MEX'),
            array('name' => 'Macedonia', 'abbr' => 'MKD'),
            array('name' => 'Mali', 'abbr' => 'MLI'),
            array('name' => 'Myanmar', 'abbr' => 'MMR'),
            array('name' => 'Montenegro', 'abbr' => 'MNE'),
            array('name' => 'Mongolia', 'abbr' => 'MNG'),
            array('name' => 'Mozambique', 'abbr' => 'MOZ'),
            array('name' => 'Mauritania', 'abbr' => 'MRT'),
            array('name' => 'Malawi', 'abbr' => 'MWI'),
            array('name' => 'Malaysia', 'abbr' => 'MYS'),
            array('name' => 'Namibia', 'abbr' => 'NAM'),
            array('name' => 'New Caledonia', 'abbr' => 'NCL'),
            array('name' => 'Niger', 'abbr' => 'NER'),
            array('name' => 'Nigeria', 'abbr' => 'NGA'),
            array('name' => 'Nicaragua', 'abbr' => 'NIC'),
            array('name' => 'Netherlands', 'abbr' => 'NLD'),
            array('name' => 'Norway', 'abbr' => 'NOR'),
            array('name' => 'Nepal', 'abbr' => 'NPL'),
            array('name' => 'New Zealand', 'abbr' => 'NZL'),
            array('name' => 'Oman', 'abbr' => 'OMN'),
            array('name' => 'Pakistan', 'abbr' => 'PAK'),
            array('name' => 'Panama', 'abbr' => 'PAN'),
            array('name' => 'Philippines', 'abbr' => 'PHL'),
            array('name' => 'Peru', 'abbr' => 'PER'),
            array('name' => 'Papua New Guinea', 'abbr' => 'PNG'),
            array('name' => 'Poland', 'abbr' => 'POL'),
            array('name' => 'Puerto Rico', 'abbr' => 'PRI'),
            array('name' => 'North Korea', 'abbr' => 'PRK'),
            array('name' => 'Portugal', 'abbr' => 'PRT'),
            array('name' => 'Paraguay', 'abbr' => 'PRY'),
            array('name' => 'Qatar', 'abbr' => 'QAT'),
            array('name' => 'Romania', 'abbr' => 'ROU'),
            array('name' => 'Russia', 'abbr' => 'RUS'),
            array('name' => 'Rwanda', 'abbr' => 'RWA'),
            array('name' => 'Western Sahara', 'abbr' => 'ESH'),
            array('name' => 'Saudi Arabia', 'abbr' => 'SAU'),
            array('name' => 'Sudan', 'abbr' => 'SDN'),
            array('name' => 'South Sudan', 'abbr' => 'SSD'),
            array('name' => 'Senegal', 'abbr' => 'SEN'),
            array('name' => 'Solomon Islands', 'abbr' => 'SLB'),
            array('name' => 'Sierra Leone', 'abbr' => 'SLE'),
            array('name' => 'El Salvador', 'abbr' => 'SLV'),
            array('name' => 'Somaliland', 'abbr' => 'SOML'),
            array('name' => 'Somalia', 'abbr' => 'SOM'),
            array('name' => 'Republic of Serbia', 'abbr' => 'SRB'),
            array('name' => 'Suriname', 'abbr' => 'SUR'),
            array('name' => 'Slovakia', 'abbr' => 'SVK'),
            array('name' => 'Slovenia', 'abbr' => 'SVN'),
            array('name' => 'Sweden', 'abbr' => 'SWE'),
            array('name' => 'Swaziland', 'abbr' => 'SWZ'),
            array('name' => 'Syria', 'abbr' => 'SYR'),
            array('name' => 'Chad', 'abbr' => 'TCD'),
            array('name' => 'Togo', 'abbr' => 'TGO'),
            array('name' => 'Thailand', 'abbr' => 'THA'),
            array('name' => 'Tajikistan', 'abbr' => 'TJK'),
            array('name' => 'Turkmenistan', 'abbr' => 'TKM'),
            array('name' => 'East Timor', 'abbr' => 'TLS'),
            array('name' => 'Trinidad and Tobago', 'abbr' => 'TTO'),
            array('name' => 'Tunisia', 'abbr' => 'TUN'),
            array('name' => 'Turkey', 'abbr' => 'TUR'),
            array('name' => 'Taiwan', 'abbr' => 'TWN'),
            array('name' => 'United Republic of Tanzania', 'abbr' => 'TZA'),
            array('name' => 'Uganda', 'abbr' => 'UGA'),
            array('name' => 'Ukraine', 'abbr' => 'UKR'),
            array('name' => 'Uruguay', 'abbr' => 'URY'),
            array('name' => 'United States of America', 'abbr' => 'USA'),
            array('name' => 'Uzbekistan', 'abbr' => 'UZB'),
            array('name' => 'Venezuela', 'abbr' => 'VEN'),
            array('name' => 'Vietnam', 'abbr' => 'VNM'),
            array('name' => 'Vanuatu', 'abbr' => 'VUT'),
            array('name' => 'West Bank', 'abbr' => 'PSE'),
            array('name' => 'Yemen', 'abbr' => 'YEM'),
            array('name' => 'South Africa', 'abbr' => 'ZAF'),
            array('name' => 'Zambia', 'abbr' => 'ZMB'),
            array('name' => 'Zimbabwe', 'abbr' => 'ZWE'),
        );

        DB::table('map_countries')->insert($countries);
    }

}



